### PR TITLE
Freekev

### PR DESCRIPTION
**Pull request by FreeKev**
Introduces the editing of scene icons, so that buttons are smaller and customizable, like typical streaming decks. This should be more friendly for mobile if a user has numerous scenes.

### CODE REVIEW

**Comment by Niek** [comment]
Thanks for the PR! This looks nice, I like it a lot.

A few suggestions:
* Can we generate a random color scheme instead of defaulting to `#fff` for the icons?
* Can we add the first letter of the scene or the scene number in the icon?
* What about the preview - is it useful to keep that when on mobile?

**Comment by FreeKev** [comment]
Thanks!

I'm thinking through those suggestions.

I don't think the first suggestion could work with the second, unfortunately, because then you would need to make sure the font color was a complimentary color to its background (sometimes they end up being the same and you can't see a thing!). I don't think we want to try that. Either that or we could give the text some ghastly shadow, which shouldn't be an option. I'm thinking it's an either-or situation. Do you have a preference? Personally, I like the idea of a randomly generated color. It's a simple solution.

As for the preview, I considered it a different issue than the styling of the icons, but I agree that on mobile I don't really feel it's necessary; nevertheless, maybe it's appropriate for a subsequent PR?

**Comment by Niek** [comment]
Actually if we generate a random color [like here](https://dev.to/akhil_001/generating-random-color-with-single-line-of-js-code-fhj) we can go with a white letter, that should be readable.
Sure, hiding preview is probably out of scope for this PR.

**Comment by FreeKev** [comment]
Per that article... If we choose a random number that generates a color between white and black (16777216 converts to 1000000 and 16777215 converts to ffffff), then it could potentially generate a white (16777215/ffffff) background, right? Then a white font would be invisible.

**Comment by FreeKev** [comment]
However, we could put the scene name under the icon, if you'd like. Something like icons/buttons on a smartphone screen.

**Comment by FreeKev** [comment]
Screen Shot 2021-01-22 at 11 16 00 AM

Here's an example. I randomly generated a color using that script and put a white "A" on it. It's legible, barely, but entirely unfriendly to accessibility best practices.

**Pull request closed without merging**
