### PR TITLE
Added Studio Mode functionality

### PR DESCRIPTION
**Pull request by isctylr**
Love your tool, but we run almost exclusively in Studio mode, so I wanted to add the functionality. Please review and you can send me edits if it doesn't fit your design spec.

### CODE REVIEW

**Comment by Niek** [comment]
Great functionality, thanks for the PR!

I'll add some comments to the code with some small requests, but the main one is:
- I'm missing a transition button between the preview and program previews, I'd be good to have that
- Switching studio mode quickly on/off for a few times get me stuck in a broken preview state. Maybe it's something in the websocket code, need to investigate it a bit more

**Comment by isctylr** [comment]
Thanks for looking into that, I'll work on it and comment once I've made the changes. Currently it takes the preview scene when its tapped again. Instead should it only transition when the transition button is pressed? (So, in studio mode, pressing a scene always puts that scene into preview, but it never takes it on program until the transition button is pressed? Or, leave it the way it is but with a transition button, and it will switch to the scene on program either when double tapped or when the transition button is pressed)

**Comment by isctylr** [comment]
Okay, I left the current double-tap functionality and added a transition button between the previews, plus catching errors. I also added a skeleton for the preview scene until getScreenshot is called again to add a preview.

**Comment by Niek** [comment]
Excellent, thanks a lot! I somehow missed "click scene again to transition", I think the transition button is a plus for usability.

I made some small cleanups and merged this PR now.

@all-contributors please add @isctylr for code and ideas

**Pull request merged**
