### PR TITLE
Added button to control the OBS Virtual Webcam

### PR DESCRIPTION
**Pull request by donahuetech**
I added the ability to start/stop the Virtual Webcam.

### CODE REVIEW

**Comment by Niek** [comment]
Thanks for the PR! It looks great (including the icon), but personally I would prefer to use `VirtualcamStateChanged` events instead of polling `GetVirtualCamStatus` every second. Can you add that?

Also a small request to run `npm run lint` before commit (I know, I need to add a husky pre-commit hook) 😄

**Comment by donahuetech** [comment]
Sure, I can take a look at making those changes this evening.

**Comment by Niek** [comment]
Perfect! Merged now 👍

**Comment by Niek** [comment]
@all-contributors please add @donahuetech for code and ideas

**Pull request merged**
