### PR TITLE
Added recording control.

### PR DESCRIPTION
**Pull request by feitosa-daniel**
Added the "Start recording" button next to "Start streaming". If either one starts, the other button disappears.

### CODE REVIEW

**Comment by Niek** [comment]
Nice addition, thanks!

What is the reason to show only 1 button at once? As far as I know there is no limitation to record + stream at the same time in OBS.

**Comment by feitosa-daniel** [comment]
There is not limitation indeed. For me, it is just to avoid clicking at the wrong buttom. But I could use different colors for each buttom or leave both as-is. I don't have any strong opinion on the matter. :-)

Would you have a particular layout in mind?

**Comment by Niek** [comment]
The best would be to make them icon-buttons like fullscreen. You can use the icons from the mdi-svelte package / https://materialdesignicons.com/.

**Comment by feitosa-daniel** [comment]
Sounds great! I will have a look at it and send a revised PR when I have it.

**Comment by feitosa-daniel** [comment]
That's the current state. Shall we keep the text or leave the icon only?

obs-web-example

obs-web-example-2

**Comment by Niek** [comment]
> That's the current state. Shall we keep the text or leave the icon only?
> 
> obs-web-example
> 
> obs-web-example-2

Excellent work! Up to you, I think the current version is fine. Let me know and I will merge this.

**Comment by feitosa-daniel** [comment]
Then let's go with the this version. :-)
Thanks for the time put on PR.

**Comment by Niek** [comment]
Great, thanks a lot!

@all-contributors please add @feitosa-daniel for code and features

**Pull request merged**
