### PR TITLE
Refactor with Svelte components, add ItemSwitcher

### PR DESCRIPTION
**Pull request by filiphanes**
- components SceneSwitcher, ItemSwitcher, ProgramPreview, SourceButton
- simplified App.svelte
- ItemSwitcher automatically detects scenes with `(switch)` in their name a creates UI for switching only 1 visible item in that scene.
- - Usable when you want to switch between many backgrounds (image or looping video) and use that scene as source in other scene. And you don't want to create new scene for each background. And you want to visually see backgrounds.
- use jpg screenshots instead of png to save traffic
- use more native css in components, less global bulma

### CODE REVIEW

**Comment by filiphanes** [comment]
Implements #34 change transitions

**Comment by Niek** [comment]
Awesome job, thanks @filiphanes! I do have a couple of remarks:

* Bumping `@rollup/plugin-commonjs` to v22 requires a newer `@rollup/plugin-node-resolve` version (try: `npm i && npm run dev`) and break loading the obs-websocket-js module, can you please check?
* There are some issues now when connecting with a password, the socket seems to disconnect immediately.

Looking forward to see this ready for merging :)

**Comment by filiphanes** [comment]
sorry, did not `npm i` after change, was trying to fix it, but without luck
password connect fixed

**Comment by filiphanes** [comment]
implemented  #55 profile selector
and scene collection selector

**Comment by filiphanes** [comment]
updated screenshot.png is needed

**Comment by Niek** [comment]
Awesome job, again @filiphanes! Merging this now :)

**Comment by Niek** [comment]
@all-contributors please add @filiphanes for code and ideas and design

**Pull request merged**
